var redis = require('redis');
exports.redis = redis.createClient(6379, '127.0.0.1');
exports.REDIS_PREFIX = "actual_queue_dev"
exports.EVENT_QUEUE_TTL = 60 * 60; // 1 hour (in seconds)
exports.USER_POLL_THRESHOLD = 60 * 30 * 1000; // 30 min (in milliseconds)
exports.USET_POLL_THRESHOLD_ONLINE = 10 * 1000; //10 sec (in milliseconds)
exports.PS_TITLE = "actual_queue";
exports.PORT = 8000;
exports.PORT_UI = 8888;